name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - ticketing/client/**
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build client image
        run: cd ticketing && cd client && docker build -t jseow5177/client .
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push client image to Docker hub
        run: docker push jseow5177/client
      - name: Set up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Create a new active context to Kubernetes cluster on Digital Ocean
        run: doctl kubernetes cluster kubeconfig save gittix
      - name: Restart client deployment
        run: kubectl rollout restart deployment client-depl
