name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - ticketing/expiration/**
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build expiration image
        run: cd ticketing && cd expiration && docker build -t jseow5177/expiration .
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push expiration image to Docker hub
        run: docker push jseow5177/expiration
      - name: Set up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Create a new active context to Kubernetes cluster on Digital Ocean
        run: doctl kubernetes cluster kubeconfig save gittix
      - name: Restart expiration deployment
        run: kubectl rollout restart deployment expiration-depl
