name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - ticketing/infra/k8s/**
      - ticketing/infra/k8s-prod/**
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Create a new active context to Kubernetes cluster on Digital Ocean
        run: doctl kubernetes cluster kubeconfig save gittix
      - name: Apply Kubernetes manifests
        run: kubectl apply -f ticketing/infra/k8s -f ticketing/infra/k8s-prod
